# Generated by Django 4.1 on 2024-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0002_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaOutCommingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_number", models.CharField(max_length=15)),
                ("params_sent", models.TextField(max_length=1000)),
                ("message_sid", models.CharField(max_length=350)),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "template_sent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="comicsmxapi.wamessagestemplates",
                    ),
                ),
            ],
        ),
    ]
