# Generated by Django 4.1 on 2024-03-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comicsmxapi", "0011_products_productsinventory_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsinventory",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Products_Inventory_Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "method_update",
                    models.CharField(
                        choices=[
                            ("Ma", "Manually"),
                            ("Me", "Meli"),
                            ("Wo", "WooCommerce"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
