# Generated by Django 4.1 on 2024-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0013_productsinventoryupdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (0, "Inactive")], default=1
            ),
        ),
    ]
