# Generated by Django 4.1 on 2024-03-31 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comicsmxapi", "0015_productsrelatedplataform"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataform_name",
                    models.CharField(
                        choices=[
                            ("Manually", "Manually"),
                            ("Meli", "Meli"),
                            ("WooCommerce", "WooCommerce"),
                        ],
                        max_length=100,
                    ),
                ),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comicsmxapi.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
