# Generated by Django 4.1 on 2024-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0017_alter_productsinventoryupdate_method_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="productsrelatedplataform",
            name="method",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=100,
            ),
        ),
    ]
