# Generated by Django 4.1 on 2024-04-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0020_companieuserrelated_companie"),
    ]

    operations = [
        migrations.AddField(
            model_name="companieuserrelated",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="comicsmxapi.companie",
            ),
            preserve_default=False,
        ),
    ]
