# Generated by Django 4.1 on 2024-04-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comicsmxapi",
            "0022_companiesplataformsrelated_companiesuserrelated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="comicsmxapi.companie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")],
                default="Active",
            ),
        ),
    ]
