# Generated by Django 4.1 on 2024-04-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0023_product_company_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
    ]
