# Generated by Django 4.1 on 2024-04-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0024_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsrelatedplataform",
            name="product_plataform_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companie",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companiesplataformsrelated",
            name="plataform",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="companiesplataformsrelated",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companiesuserrelated",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wamessagestemplates",
            name="status",
            field=models.IntegerField(
                choices=[("Active", "Active"), ("Invactive", "Inactive")], default=1
            ),
        ),
    ]
