# Generated by Django 4.1 on 2024-04-17 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comicsmxapi", "0025_productsrelatedplataform_product_plataform_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPlataformRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataform",
                    models.CharField(
                        choices=[
                            ("manually", "Manually"),
                            ("mercado libre", "Mercado Libre"),
                            ("woocommerce", "WooCommerce"),
                        ],
                        max_length=250,
                    ),
                ),
                ("order_plataform_id", models.CharField(max_length=500)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.TextField(max_length=10000)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Invactive", "Inactive")],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comicsmxapi.companie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
