# Generated by Django 4.1 on 2024-04-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0026_orderplataformrelated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companie",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companiesplataformsrelated",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companiesuserrelated",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="wamessagestemplates",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=150,
            ),
        ),
    ]
