# Generated by Django 4.1 on 2024-04-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0027_alter_companie_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplataformrelated",
            name="date_order",
            field=models.DateTimeField(null=True, verbose_name="date order"),
        ),
        migrations.AddField(
            model_name="orderplataformrelated",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
