# Generated by Django 4.2.1 on 2024-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0029_productupdatedlog_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsinventoryupdate",
            name="action_type",
            field=models.CharField(
                choices=[("increment", "Increment"), ("decrement", "Decrement")],
                default="increment",
                max_length=100,
            ),
        ),
    ]
