# Generated by Django 4.2.1 on 2024-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0030_productsinventoryupdate_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsrelatedplataform",
            name="product_plataform_id",
            field=models.CharField(max_length=250),
        ),
    ]
