# Generated by Django 4.2.1 on 2024-05-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0032_alter_orderplataformrelated_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companiesplataformsrelated",
            name="plataform",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="plataform",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pendding", "Pendding to pay"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("delivery", "Delivery"),
                    ("shipping", "Shipping"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productsinventoryupdate",
            name="method_update",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productsprice",
            name="plataform_name",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productsrelatedplataform",
            name="method",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productupdatedlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("manually", "Manually"),
                    ("mercado_libre", "Mercado Libre"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=100,
            ),
        ),
    ]
