# Generated by Django 4.2.1 on 2024-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0036_customer_alter_orderplataformrelated_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customernotifications",
            name="data",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pendding", "Pendding to pay"),
                    ("failed", "Failed"),
                    ("paid", "Paid"),
                    ("shipping", "Shipping"),
                    ("delivery", "Delivery"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
