# Generated by Django 4.2.1 on 2024-05-10 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comicsmxapi", "0037_customernotifications_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="status",
            field=models.CharField(
                choices=[
                    ("shipping", "Shipping"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("delivery", "Delivery"),
                    ("pendding", "Pendding to pay"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ProductMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=10000, null=True),
                ),
                ("images", models.TextField(blank=True, max_length=10000, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "width",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "length",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="comicsmxapi.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
