# Generated by Django 4.2.1 on 2024-05-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsmxapi", "0038_alter_orderplataformrelated_status_productmeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplataformrelated",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivery", "Delivery"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("pendding", "Pendding to pay"),
                    ("paid", "Paid"),
                    ("shipping", "Shipping"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productmeta",
            name="weight",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
