# Generated by Django 4.2.1 on 2024-06-06 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comicsmxapi', '0041_alter_orderplataformrelated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('delivery', 'Delivery'), ('paid', 'Paid'), ('shipping', 'Shipping'), ('pendding', 'Pendding to pay')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ShipProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=250)),
                ('provider_slug', models.CharField(max_length=250)),
                ('provider_url', models.CharField(max_length=250)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
