# Generated by Django 4.2.1 on 2024-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0042_alter_orderplataformrelated_status_shipproviders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiplog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('pendding', 'Pendding to pay'), ('paid', 'Paid'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
