# Generated by Django 4.2.1 on 2024-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0043_shiplog_alter_orderplataformrelated_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField(max_length=100000)),
                ('body', models.TextField(max_length=100000)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('pendding', 'Pendding to pay'), ('shipping', 'Shipping'), ('completed', 'Completed'), ('delivery', 'Delivery'), ('failed', 'Failed'), ('paid', 'Paid')], default='pending', max_length=50),
        ),
    ]
