# Generated by Django 4.2.1 on 2024-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0044_apilog_alter_orderplataformrelated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='origin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('shipping', 'Shipping'), ('failed', 'Failed'), ('pendding', 'Pendding to pay'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
