# Generated by Django 4.2.1 on 2024-07-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0048_apilog_method_alter_orderplataformrelated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('delivery', 'Delivery'), ('shipping', 'Shipping'), ('failed', 'Failed'), ('completed', 'Completed'), ('pendding', 'Pendding to pay')], default='pending', max_length=50),
        ),
    ]
