# Generated by Django 4.2.1 on 2024-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0049_customer_status_alter_orderplataformrelated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotifications',
            name='type_notification',
            field=models.CharField(choices=[('order_recived', 'Orden Recibida'), ('order_shipped', 'Orden Enviada'), ('order_delivery', 'Orden Entregada')], default='order_recived', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('paid', 'Paid'), ('pendding', 'Pendding to pay'), ('failed', 'Failed'), ('completed', 'Completed'), ('shipping', 'Shipping')], default='pending', max_length=50),
        ),
    ]
