# Generated by Django 4.2.1 on 2024-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsmxapi', '0050_customernotifications_type_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinventoryupdate',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='companiesplataformsrelated',
            name='plataform',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=250),
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='plataform',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=250),
        ),
        migrations.AlterField(
            model_name='orderplataformrelated',
            name='status',
            field=models.CharField(choices=[('pendding', 'Pendding to pay'), ('delivery', 'Delivery'), ('shipping', 'Shipping'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsinventoryupdate',
            name='method_update',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productsprice',
            name='plataform_name',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productsrelatedplataform',
            name='method',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productupdatedlog',
            name='method',
            field=models.CharField(choices=[('manually', 'Manually'), ('mercado_libre', 'Mercado Libre'), ('woocommerce', 'WooCommerce'), ('walmart', 'Walmart')], max_length=100),
        ),
    ]
